security:
    password_hashers:
        App\Entity\User: auto
        Symfony\Component\Security\Core\User\User: auto
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_MODO, ROLE_USER ]
    providers:
        chain_provider:
            chain:
                providers: [my_entity_user_provider]
        my_entity_user_provider:
            entity: { class: App\Entity\User}
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: chain_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                remember_me: true
                default_target_path: login
                always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager
                failure_path: home
            logout:
                path: logout
                target: home
                invalidate_session: false
            access_denied_handler: App\Security\AccessDeniedHandler
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 31104000
                samesite: 'lax'
                path:     /
                always_remember_me: true
                secure: true
                name: 'area_remember'
                token_provider: 'Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider'

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(HTTPS_SCHEMA)%' }
        - { path: ^/connect, roles: ROLE_USER, requires_channel: '%env(HTTPS_SCHEMA)%' }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(HTTPS_SCHEMA)%' }
