vich_uploader:
    db_driver: orm

    mappings:
            user_img:
                uri_prefix: /user/img
                upload_destination: '%kernel.project_dir%/public/user/img'
            planet_img:
                uri_prefix: /img
                upload_destination: '%kernel.project_dir%/public/img'