#!/bin/bash

while true
do
    curl "http://areauniverse.ddns.net/resources/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
    sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
curl "http://areauniverse.ddns.net/construction/"
sleep 1
done
