#!/bin/bash

while true
do
    curl "http://www.areauniverse.eu/resources/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
    curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
    curl "http://www.areauniverse.eu/construction/"
curl "http://www.areauniverse.eu/clash/"
    sleep 1
done
