#!/bin/bash

while true
do
    curl "http://areauniverse.ddns.net/resources/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
    curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
    curl "http://areauniverse.ddns.net/construction/"
curl "http://areauniverse.ddns.net/clash/"
    sleep 1
done
