<?php declare(strict_types = 1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180422160541 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE ally_war (id INT AUTO_INCREMENT NOT NULL, ally_id INT DEFAULT NULL, allyTag VARCHAR(5) NOT NULL, signedAt DATETIME NOT NULL, accepted TINYINT(1) NOT NULL, INDEX IDX_BEBC3F951C6E3E76 (ally_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_terraformation (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level TINYINT(1) NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE orbite (id INT AUTO_INCREMENT NOT NULL, ship_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_6BD04981C256317D (ship_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fleet (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, ship_id INT DEFAULT NULL, soldier_id INT DEFAULT NULL, worker_id INT DEFAULT NULL, scientist_id INT DEFAULT NULL, INDEX IDX_A05E1E47A76ED395 (user_id), UNIQUE INDEX UNIQ_A05E1E47C256317D (ship_id), UNIQUE INDEX UNIQ_A05E1E47A38C1700 (soldier_id), UNIQUE INDEX UNIQ_A05E1E476B20BA36 (worker_id), UNIQUE INDEX UNIQ_A05E1E47EBA327D6 (scientist_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_demography (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ally_allied (id INT AUTO_INCREMENT NOT NULL, ally_id INT DEFAULT NULL, allyTag VARCHAR(5) NOT NULL, signedAt DATETIME NOT NULL, accepted TINYINT(1) NOT NULL, INDEX IDX_161AB9BB1C6E3E76 (ally_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE y_colonizer (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, bitcoin INT NOT NULL, amount BIGINT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, signature INT NOT NULL, armor INT NOT NULL, shield INT NOT NULL, missile INT NOT NULL, laser INT NOT NULL, plasma INT NOT NULL, cargo INT NOT NULL, speed INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE y_barge (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, bitcoin INT NOT NULL, amount BIGINT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, signature INT NOT NULL, armor INT NOT NULL, shield INT NOT NULL, missile INT NOT NULL, laser INT NOT NULL, plasma INT NOT NULL, cargo INT NOT NULL, speed INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_buildSearch (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, production NUMERIC(9, 5) NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE soldier (id INT AUTO_INCREMENT NOT NULL, amount BIGINT NOT NULL, life INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_lightUsine (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, level TINYINT(1) NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE planet (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, building_id INT DEFAULT NULL, orbite_id INT DEFAULT NULL, ship_id INT DEFAULT NULL, soldier_id INT DEFAULT NULL, worker_id INT DEFAULT NULL, scientist_id INT DEFAULT NULL, sector_id INT DEFAULT NULL, name VARCHAR(15) DEFAULT NULL, niobium NUMERIC(28, 5) NOT NULL, water NUMERIC(28, 5) NOT NULL, position INT NOT NULL, ground INT DEFAULT NULL, groundPlace INT DEFAULT NULL, sky INT DEFAULT NULL, skyPlace INT DEFAULT NULL, empty TINYINT(1) NOT NULL, imageName VARCHAR(20) DEFAULT NULL, INDEX IDX_68136AA5A76ED395 (user_id), UNIQUE INDEX UNIQ_68136AA54D2A7E12 (building_id), UNIQUE INDEX UNIQ_68136AA521DE9274 (orbite_id), UNIQUE INDEX UNIQ_68136AA5C256317D (ship_id), UNIQUE INDEX UNIQ_68136AA5A38C1700 (soldier_id), UNIQUE INDEX UNIQ_68136AA56B20BA36 (worker_id), UNIQUE INDEX UNIQ_68136AA5EBA327D6 (scientist_id), INDEX IDX_68136AA5DE95C867 (sector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE y_recycleur (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, bitcoin INT NOT NULL, amount BIGINT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, signature INT NOT NULL, armor INT NOT NULL, shield INT NOT NULL, missile INT NOT NULL, laser INT NOT NULL, plasma INT NOT NULL, cargo INT NOT NULL, speed INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE galaxy (id INT AUTO_INCREMENT NOT NULL, position INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ship (id INT AUTO_INCREMENT NOT NULL, fleet_id INT DEFAULT NULL, orbite_id INT DEFAULT NULL, planet_id INT DEFAULT NULL, sonde_id INT DEFAULT NULL, colonizer_id INT DEFAULT NULL, recycleur_id INT DEFAULT NULL, barge_id INT DEFAULT NULL, hunter_id INT DEFAULT NULL, fregate_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_FA30EB244B061DF9 (fleet_id), UNIQUE INDEX UNIQ_FA30EB2421DE9274 (orbite_id), UNIQUE INDEX UNIQ_FA30EB24A25E9820 (planet_id), UNIQUE INDEX UNIQ_FA30EB24F1B7D1A2 (sonde_id), UNIQUE INDEX UNIQ_FA30EB24D726A9F2 (colonizer_id), UNIQUE INDEX UNIQ_FA30EB24D7B82D29 (recycleur_id), UNIQUE INDEX UNIQ_FA30EB24222D237A (barge_id), UNIQUE INDEX UNIQ_FA30EB24A7DC5C81 (hunter_id), UNIQUE INDEX UNIQ_FA30EB246D3EAA45 (fregate_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ally (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(15) NOT NULL, sigle VARCHAR(5) NOT NULL, slogan VARCHAR(30) NOT NULL, bitcoin BIGINT NOT NULL, taxe INT NOT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_382900D5E237E06 (name), UNIQUE INDEX UNIQ_382900D8776B952 (sigle), UNIQUE INDEX UNIQ_382900D988768C9 (slogan), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_cargo (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE grade (id INT AUTO_INCREMENT NOT NULL, ally_id INT DEFAULT NULL, placement INT NOT NULL, name VARCHAR(20) NOT NULL, canRecruit TINYINT(1) NOT NULL, canKick TINYINT(1) NOT NULL, canWar TINYINT(1) NOT NULL, canPeace TINYINT(1) NOT NULL, INDEX IDX_595AAE341C6E3E76 (ally_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_extractor (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, production NUMERIC(9, 5) NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_lightShip (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_heavyUsine (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, level TINYINT(1) NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE research (id INT AUTO_INCREMENT NOT NULL, onde_id INT DEFAULT NULL, industry_id INT DEFAULT NULL, discipline_id INT DEFAULT NULL, hyperespace_id INT DEFAULT NULL, barge_id INT DEFAULT NULL, utility_id INT DEFAULT NULL, demography_id INT DEFAULT NULL, terraformation_id INT DEFAULT NULL, cargo_id INT DEFAULT NULL, recycleur_id INT DEFAULT NULL, armement_id INT DEFAULT NULL, missile_id INT DEFAULT NULL, laser_id INT DEFAULT NULL, plasma_id INT DEFAULT NULL, lightShip_id INT DEFAULT NULL, heavyShip_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_57EB50C22B2647C6 (onde_id), UNIQUE INDEX UNIQ_57EB50C22B19A734 (industry_id), UNIQUE INDEX UNIQ_57EB50C211093B1B (lightShip_id), UNIQUE INDEX UNIQ_57EB50C2EA0C6ED6 (heavyShip_id), UNIQUE INDEX UNIQ_57EB50C2A5522701 (discipline_id), UNIQUE INDEX UNIQ_57EB50C2F4AA385D (hyperespace_id), UNIQUE INDEX UNIQ_57EB50C2222D237A (barge_id), UNIQUE INDEX UNIQ_57EB50C27189C2DB (utility_id), UNIQUE INDEX UNIQ_57EB50C21C829638 (demography_id), UNIQUE INDEX UNIQ_57EB50C2C220B9DF (terraformation_id), UNIQUE INDEX UNIQ_57EB50C2813AC380 (cargo_id), UNIQUE INDEX UNIQ_57EB50C2D7B82D29 (recycleur_id), UNIQUE INDEX UNIQ_57EB50C2D4413494 (armement_id), UNIQUE INDEX UNIQ_57EB50C22ECD5341 (missile_id), UNIQUE INDEX UNIQ_57EB50C24BF5DEAB (laser_id), UNIQUE INDEX UNIQ_57EB50C24AA16509 (plasma_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE y_fregate (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, amount BIGINT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, signature INT NOT NULL, armor INT NOT NULL, shield INT NOT NULL, missile INT NOT NULL, laser INT NOT NULL, plasma INT NOT NULL, cargo INT NOT NULL, speed INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_hyperespace (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level TINYINT(1) NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_users (id INT AUTO_INCREMENT NOT NULL, ally_id INT DEFAULT NULL, research_id INT DEFAULT NULL, grade_id INT DEFAULT NULL, rank_id INT DEFAULT NULL, username VARCHAR(20) NOT NULL, email VARCHAR(40) NOT NULL, joinAllyAt DATETIME DEFAULT NULL, password VARCHAR(64) NOT NULL, bitcoin NUMERIC(28, 5) NOT NULL, created_at DATETIME NOT NULL, connected TINYINT(1) NOT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_C2502824F85E0677 (username), UNIQUE INDEX UNIQ_C2502824E7927C74 (email), INDEX IDX_C25028241C6E3E76 (ally_id), UNIQUE INDEX UNIQ_C25028247909E1ED (research_id), INDEX IDX_C2502824FE19A1A8 (grade_id), UNIQUE INDEX UNIQ_C25028247616678F (rank_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE y_sonde (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, amount BIGINT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, signature INT NOT NULL, armor INT NOT NULL, shield INT NOT NULL, missile INT NOT NULL, laser INT NOT NULL, plasma INT NOT NULL, cargo INT NOT NULL, speed INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_plasma (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_onde (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_missile (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sector (id INT AUTO_INCREMENT NOT NULL, galaxy_id INT DEFAULT NULL, position INT NOT NULL, INDEX IDX_4BA3D9E8B61FAB2 (galaxy_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ally_proposal (id INT AUTO_INCREMENT NOT NULL, ally_id INT DEFAULT NULL, user_id INT DEFAULT NULL, proposalAt DATETIME NOT NULL, INDEX IDX_D6F70BC11C6E3E76 (ally_id), INDEX IDX_D6F70BC1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scientist (id INT AUTO_INCREMENT NOT NULL, amount BIGINT NOT NULL, life INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE building (id INT AUTO_INCREMENT NOT NULL, miner_id INT DEFAULT NULL, extractor_id INT DEFAULT NULL, metropole_id INT DEFAULT NULL, city_id INT DEFAULT NULL, caserne_id INT DEFAULT NULL, radar_id INT DEFAULT NULL, spaceShip_id INT DEFAULT NULL, buildSearch_id INT DEFAULT NULL, skyRadar_id INT DEFAULT NULL, skyBrouilleur_id INT DEFAULT NULL, lightUsine_id INT DEFAULT NULL, heavyUsine_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_E16F61D4BF88117 (miner_id), UNIQUE INDEX UNIQ_E16F61D4DBCA8D53 (extractor_id), UNIQUE INDEX UNIQ_E16F61D485646CF7 (spaceShip_id), UNIQUE INDEX UNIQ_E16F61D42D15FD1C (buildSearch_id), UNIQUE INDEX UNIQ_E16F61D4186701AE (metropole_id), UNIQUE INDEX UNIQ_E16F61D48BAC62AF (city_id), UNIQUE INDEX UNIQ_E16F61D49C03C926 (caserne_id), UNIQUE INDEX UNIQ_E16F61D4C9976951 (radar_id), UNIQUE INDEX UNIQ_E16F61D42C83DB79 (skyRadar_id), UNIQUE INDEX UNIQ_E16F61D4EA5D5F6 (skyBrouilleur_id), UNIQUE INDEX UNIQ_E16F61D464119DE1 (lightUsine_id), UNIQUE INDEX UNIQ_E16F61D4813F26B9 (heavyUsine_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE worker (id INT AUTO_INCREMENT NOT NULL, amount NUMERIC(28, 5) NOT NULL, life INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_skyBrouilleur (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, sky INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_radar (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_utility (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rank (id INT AUTO_INCREMENT NOT NULL, point BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_barge (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level TINYINT(1) NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_caserne (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, production NUMERIC(9, 5) NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ally_pna (id INT AUTO_INCREMENT NOT NULL, ally_id INT DEFAULT NULL, allyTag VARCHAR(5) NOT NULL, signedAt DATETIME NOT NULL, accepted TINYINT(1) NOT NULL, INDEX IDX_B8D574011C6E3E76 (ally_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_metropole (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, production NUMERIC(9, 5) NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, sky INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_recycleur (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level TINYINT(1) NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_laser (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_armement (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_heavyShip (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_industry (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_spaceShip (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, production NUMERIC(9, 5) NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, sky INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_admins (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(20) NOT NULL, email VARCHAR(40) NOT NULL, password VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_47E3788FF85E0677 (username), UNIQUE INDEX UNIQ_47E3788FE7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE z_discipline (id INT AUTO_INCREMENT NOT NULL, bitcoin INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_city (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, production NUMERIC(9, 5) NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_miner (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, production NUMERIC(9, 5) NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, ground INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE x_skyRadar (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, level INT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, sky INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE y_hunter (id INT AUTO_INCREMENT NOT NULL, niobium INT NOT NULL, water INT NOT NULL, amount BIGINT NOT NULL, finishAt DATETIME DEFAULT NULL, constructTime BIGINT NOT NULL, signature INT NOT NULL, armor INT NOT NULL, shield INT NOT NULL, missile INT NOT NULL, laser INT NOT NULL, plasma INT NOT NULL, cargo INT NOT NULL, speed INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE ally_war ADD CONSTRAINT FK_BEBC3F951C6E3E76 FOREIGN KEY (ally_id) REFERENCES ally (id)');
        $this->addSql('ALTER TABLE orbite ADD CONSTRAINT FK_6BD04981C256317D FOREIGN KEY (ship_id) REFERENCES ship (id)');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E47A76ED395 FOREIGN KEY (user_id) REFERENCES app_users (id)');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E47C256317D FOREIGN KEY (ship_id) REFERENCES ship (id)');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E47A38C1700 FOREIGN KEY (soldier_id) REFERENCES soldier (id)');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E476B20BA36 FOREIGN KEY (worker_id) REFERENCES worker (id)');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E47EBA327D6 FOREIGN KEY (scientist_id) REFERENCES scientist (id)');
        $this->addSql('ALTER TABLE ally_allied ADD CONSTRAINT FK_161AB9BB1C6E3E76 FOREIGN KEY (ally_id) REFERENCES ally (id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA5A76ED395 FOREIGN KEY (user_id) REFERENCES app_users (id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA54D2A7E12 FOREIGN KEY (building_id) REFERENCES building (id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA521DE9274 FOREIGN KEY (orbite_id) REFERENCES orbite (id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA5C256317D FOREIGN KEY (ship_id) REFERENCES ship (id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA5A38C1700 FOREIGN KEY (soldier_id) REFERENCES soldier (id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA56B20BA36 FOREIGN KEY (worker_id) REFERENCES worker (id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA5EBA327D6 FOREIGN KEY (scientist_id) REFERENCES scientist (id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA5DE95C867 FOREIGN KEY (sector_id) REFERENCES sector (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB244B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleet (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB2421DE9274 FOREIGN KEY (orbite_id) REFERENCES orbite (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB24A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB24F1B7D1A2 FOREIGN KEY (sonde_id) REFERENCES y_sonde (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB24D726A9F2 FOREIGN KEY (colonizer_id) REFERENCES y_colonizer (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB24D7B82D29 FOREIGN KEY (recycleur_id) REFERENCES y_recycleur (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB24222D237A FOREIGN KEY (barge_id) REFERENCES y_barge (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB24A7DC5C81 FOREIGN KEY (hunter_id) REFERENCES y_hunter (id)');
        $this->addSql('ALTER TABLE ship ADD CONSTRAINT FK_FA30EB246D3EAA45 FOREIGN KEY (fregate_id) REFERENCES y_fregate (id)');
        $this->addSql('ALTER TABLE grade ADD CONSTRAINT FK_595AAE341C6E3E76 FOREIGN KEY (ally_id) REFERENCES ally (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C22B2647C6 FOREIGN KEY (onde_id) REFERENCES z_onde (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C22B19A734 FOREIGN KEY (industry_id) REFERENCES z_industry (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C211093B1B FOREIGN KEY (lightShip_id) REFERENCES z_lightShip (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C2EA0C6ED6 FOREIGN KEY (heavyShip_id) REFERENCES z_heavyShip (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C2A5522701 FOREIGN KEY (discipline_id) REFERENCES z_discipline (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C2F4AA385D FOREIGN KEY (hyperespace_id) REFERENCES z_hyperespace (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C2222D237A FOREIGN KEY (barge_id) REFERENCES z_barge (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C27189C2DB FOREIGN KEY (utility_id) REFERENCES z_utility (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C21C829638 FOREIGN KEY (demography_id) REFERENCES z_demography (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C2C220B9DF FOREIGN KEY (terraformation_id) REFERENCES z_terraformation (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C2813AC380 FOREIGN KEY (cargo_id) REFERENCES z_cargo (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C2D7B82D29 FOREIGN KEY (recycleur_id) REFERENCES z_recycleur (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C2D4413494 FOREIGN KEY (armement_id) REFERENCES z_armement (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C22ECD5341 FOREIGN KEY (missile_id) REFERENCES z_missile (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C24BF5DEAB FOREIGN KEY (laser_id) REFERENCES z_laser (id)');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C24AA16509 FOREIGN KEY (plasma_id) REFERENCES z_plasma (id)');
        $this->addSql('ALTER TABLE app_users ADD CONSTRAINT FK_C25028241C6E3E76 FOREIGN KEY (ally_id) REFERENCES ally (id)');
        $this->addSql('ALTER TABLE app_users ADD CONSTRAINT FK_C25028247909E1ED FOREIGN KEY (research_id) REFERENCES research (id)');
        $this->addSql('ALTER TABLE app_users ADD CONSTRAINT FK_C2502824FE19A1A8 FOREIGN KEY (grade_id) REFERENCES grade (id)');
        $this->addSql('ALTER TABLE app_users ADD CONSTRAINT FK_C25028247616678F FOREIGN KEY (rank_id) REFERENCES rank (id)');
        $this->addSql('ALTER TABLE sector ADD CONSTRAINT FK_4BA3D9E8B61FAB2 FOREIGN KEY (galaxy_id) REFERENCES galaxy (id)');
        $this->addSql('ALTER TABLE ally_proposal ADD CONSTRAINT FK_D6F70BC11C6E3E76 FOREIGN KEY (ally_id) REFERENCES ally (id)');
        $this->addSql('ALTER TABLE ally_proposal ADD CONSTRAINT FK_D6F70BC1A76ED395 FOREIGN KEY (user_id) REFERENCES app_users (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4BF88117 FOREIGN KEY (miner_id) REFERENCES x_miner (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4DBCA8D53 FOREIGN KEY (extractor_id) REFERENCES x_extractor (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D485646CF7 FOREIGN KEY (spaceShip_id) REFERENCES x_spaceShip (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D42D15FD1C FOREIGN KEY (buildSearch_id) REFERENCES x_buildSearch (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4186701AE FOREIGN KEY (metropole_id) REFERENCES x_metropole (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D48BAC62AF FOREIGN KEY (city_id) REFERENCES x_city (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D49C03C926 FOREIGN KEY (caserne_id) REFERENCES x_caserne (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4C9976951 FOREIGN KEY (radar_id) REFERENCES x_radar (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D42C83DB79 FOREIGN KEY (skyRadar_id) REFERENCES x_skyRadar (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4EA5D5F6 FOREIGN KEY (skyBrouilleur_id) REFERENCES x_skyBrouilleur (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D464119DE1 FOREIGN KEY (lightUsine_id) REFERENCES x_lightUsine (id)');
        $this->addSql('ALTER TABLE building ADD CONSTRAINT FK_E16F61D4813F26B9 FOREIGN KEY (heavyUsine_id) REFERENCES x_heavyUsine (id)');
        $this->addSql('ALTER TABLE ally_pna ADD CONSTRAINT FK_B8D574011C6E3E76 FOREIGN KEY (ally_id) REFERENCES ally (id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C2C220B9DF');
        $this->addSql('ALTER TABLE planet DROP FOREIGN KEY FK_68136AA521DE9274');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB2421DE9274');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB244B061DF9');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C21C829638');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB24D726A9F2');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB24222D237A');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D42D15FD1C');
        $this->addSql('ALTER TABLE fleet DROP FOREIGN KEY FK_A05E1E47A38C1700');
        $this->addSql('ALTER TABLE planet DROP FOREIGN KEY FK_68136AA5A38C1700');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D464119DE1');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB24A25E9820');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB24D7B82D29');
        $this->addSql('ALTER TABLE sector DROP FOREIGN KEY FK_4BA3D9E8B61FAB2');
        $this->addSql('ALTER TABLE orbite DROP FOREIGN KEY FK_6BD04981C256317D');
        $this->addSql('ALTER TABLE fleet DROP FOREIGN KEY FK_A05E1E47C256317D');
        $this->addSql('ALTER TABLE planet DROP FOREIGN KEY FK_68136AA5C256317D');
        $this->addSql('ALTER TABLE ally_war DROP FOREIGN KEY FK_BEBC3F951C6E3E76');
        $this->addSql('ALTER TABLE ally_allied DROP FOREIGN KEY FK_161AB9BB1C6E3E76');
        $this->addSql('ALTER TABLE grade DROP FOREIGN KEY FK_595AAE341C6E3E76');
        $this->addSql('ALTER TABLE app_users DROP FOREIGN KEY FK_C25028241C6E3E76');
        $this->addSql('ALTER TABLE ally_proposal DROP FOREIGN KEY FK_D6F70BC11C6E3E76');
        $this->addSql('ALTER TABLE ally_pna DROP FOREIGN KEY FK_B8D574011C6E3E76');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C2813AC380');
        $this->addSql('ALTER TABLE app_users DROP FOREIGN KEY FK_C2502824FE19A1A8');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D4DBCA8D53');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C211093B1B');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D4813F26B9');
        $this->addSql('ALTER TABLE app_users DROP FOREIGN KEY FK_C25028247909E1ED');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB246D3EAA45');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C2F4AA385D');
        $this->addSql('ALTER TABLE fleet DROP FOREIGN KEY FK_A05E1E47A76ED395');
        $this->addSql('ALTER TABLE planet DROP FOREIGN KEY FK_68136AA5A76ED395');
        $this->addSql('ALTER TABLE ally_proposal DROP FOREIGN KEY FK_D6F70BC1A76ED395');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB24F1B7D1A2');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C24AA16509');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C22B2647C6');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C22ECD5341');
        $this->addSql('ALTER TABLE planet DROP FOREIGN KEY FK_68136AA5DE95C867');
        $this->addSql('ALTER TABLE fleet DROP FOREIGN KEY FK_A05E1E47EBA327D6');
        $this->addSql('ALTER TABLE planet DROP FOREIGN KEY FK_68136AA5EBA327D6');
        $this->addSql('ALTER TABLE planet DROP FOREIGN KEY FK_68136AA54D2A7E12');
        $this->addSql('ALTER TABLE fleet DROP FOREIGN KEY FK_A05E1E476B20BA36');
        $this->addSql('ALTER TABLE planet DROP FOREIGN KEY FK_68136AA56B20BA36');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D4EA5D5F6');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D4C9976951');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C27189C2DB');
        $this->addSql('ALTER TABLE app_users DROP FOREIGN KEY FK_C25028247616678F');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C2222D237A');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D49C03C926');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D4186701AE');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C2D7B82D29');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C24BF5DEAB');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C2D4413494');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C2EA0C6ED6');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C22B19A734');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D485646CF7');
        $this->addSql('ALTER TABLE research DROP FOREIGN KEY FK_57EB50C2A5522701');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D48BAC62AF');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D4BF88117');
        $this->addSql('ALTER TABLE building DROP FOREIGN KEY FK_E16F61D42C83DB79');
        $this->addSql('ALTER TABLE ship DROP FOREIGN KEY FK_FA30EB24A7DC5C81');
        $this->addSql('DROP TABLE ally_war');
        $this->addSql('DROP TABLE z_terraformation');
        $this->addSql('DROP TABLE orbite');
        $this->addSql('DROP TABLE fleet');
        $this->addSql('DROP TABLE z_demography');
        $this->addSql('DROP TABLE ally_allied');
        $this->addSql('DROP TABLE y_colonizer');
        $this->addSql('DROP TABLE y_barge');
        $this->addSql('DROP TABLE x_buildSearch');
        $this->addSql('DROP TABLE soldier');
        $this->addSql('DROP TABLE x_lightUsine');
        $this->addSql('DROP TABLE planet');
        $this->addSql('DROP TABLE y_recycleur');
        $this->addSql('DROP TABLE galaxy');
        $this->addSql('DROP TABLE ship');
        $this->addSql('DROP TABLE ally');
        $this->addSql('DROP TABLE z_cargo');
        $this->addSql('DROP TABLE grade');
        $this->addSql('DROP TABLE x_extractor');
        $this->addSql('DROP TABLE z_lightShip');
        $this->addSql('DROP TABLE x_heavyUsine');
        $this->addSql('DROP TABLE research');
        $this->addSql('DROP TABLE y_fregate');
        $this->addSql('DROP TABLE z_hyperespace');
        $this->addSql('DROP TABLE app_users');
        $this->addSql('DROP TABLE y_sonde');
        $this->addSql('DROP TABLE z_plasma');
        $this->addSql('DROP TABLE z_onde');
        $this->addSql('DROP TABLE z_missile');
        $this->addSql('DROP TABLE sector');
        $this->addSql('DROP TABLE ally_proposal');
        $this->addSql('DROP TABLE scientist');
        $this->addSql('DROP TABLE building');
        $this->addSql('DROP TABLE worker');
        $this->addSql('DROP TABLE x_skyBrouilleur');
        $this->addSql('DROP TABLE x_radar');
        $this->addSql('DROP TABLE z_utility');
        $this->addSql('DROP TABLE rank');
        $this->addSql('DROP TABLE z_barge');
        $this->addSql('DROP TABLE x_caserne');
        $this->addSql('DROP TABLE ally_pna');
        $this->addSql('DROP TABLE x_metropole');
        $this->addSql('DROP TABLE z_recycleur');
        $this->addSql('DROP TABLE z_laser');
        $this->addSql('DROP TABLE z_armement');
        $this->addSql('DROP TABLE z_heavyShip');
        $this->addSql('DROP TABLE z_industry');
        $this->addSql('DROP TABLE x_spaceShip');
        $this->addSql('DROP TABLE app_admins');
        $this->addSql('DROP TABLE z_discipline');
        $this->addSql('DROP TABLE x_city');
        $this->addSql('DROP TABLE x_miner');
        $this->addSql('DROP TABLE x_skyRadar');
        $this->addSql('DROP TABLE y_hunter');
    }
}
